disabled_rules: # rule identifiers to exclude from running
      - line_length
      - file_length
      - function_body_length
excluded: # paths to ignore during linting. Takes precedence over `included`.
      - Pods
      - RankTree/Library
variable_name:
      excluded:
          - id
identifier_name:
      excluded:
          - id
